//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	objectbucket_iov1alpha1 "github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1"
	"github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockStorageStatus) DeepCopyInto(out *BlockStorageStatus) {
	*out = *in
	if in.CephBlockPools != nil {
		in, out := &in.CephBlockPools, &out.CephBlockPools
		*out = make(map[string]*v1.CephBlockPoolStatus, len(*in))
		for key, val := range *in {
			var outVal *v1.CephBlockPoolStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.CephBlockPoolStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockStorageStatus.
func (in *BlockStorageStatus) DeepCopy() *BlockStorageStatus {
	if in == nil {
		return nil
	}
	out := new(BlockStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephClient) DeepCopyInto(out *CephClient) {
	*out = *in
	in.ClientSpec.DeepCopyInto(&out.ClientSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephClient.
func (in *CephClient) DeepCopy() *CephClient {
	if in == nil {
		return nil
	}
	out := new(CephClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephClusterHealthCheckSpec) DeepCopyInto(out *CephClusterHealthCheckSpec) {
	*out = *in
	in.DaemonHealth.DeepCopyInto(&out.DaemonHealth)
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = make(map[v1.KeyType]*v1.ProbeSpec, len(*in))
		for key, val := range *in {
			var outVal *v1.ProbeSpec
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.ProbeSpec)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = make(map[v1.KeyType]*v1.ProbeSpec, len(*in))
		for key, val := range *in {
			var outVal *v1.ProbeSpec
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.ProbeSpec)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephClusterHealthCheckSpec.
func (in *CephClusterHealthCheckSpec) DeepCopy() *CephClusterHealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(CephClusterHealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephClusterSpecVersion) DeepCopyInto(out *CephClusterSpecVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephClusterSpecVersion.
func (in *CephClusterSpecVersion) DeepCopy() *CephClusterSpecVersion {
	if in == nil {
		return nil
	}
	out := new(CephClusterSpecVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDaemonsStatus) DeepCopyInto(out *CephDaemonsStatus) {
	*out = *in
	if in.CephDaemons != nil {
		in, out := &in.CephDaemons, &out.CephDaemons
		*out = make(map[string]DaemonStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.CephCSIDaemons != nil {
		in, out := &in.CephCSIDaemons, &out.CephCSIDaemons
		*out = make(map[string]DaemonStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.CephCSIPluginDaemons != nil {
		in, out := &in.CephCSIPluginDaemons, &out.CephCSIPluginDaemons
		*out = make(map[string]DaemonStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDaemonsStatus.
func (in *CephDaemonsStatus) DeepCopy() *CephDaemonsStatus {
	if in == nil {
		return nil
	}
	out := new(CephDaemonsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeployment) DeepCopyInto(out *CephDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeployment.
func (in *CephDeployment) DeepCopy() *CephDeployment {
	if in == nil {
		return nil
	}
	out := new(CephDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentCert) DeepCopyInto(out *CephDeploymentCert) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentCert.
func (in *CephDeploymentCert) DeepCopy() *CephDeploymentCert {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentCustomIngress) DeepCopyInto(out *CephDeploymentCustomIngress) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentCustomIngress.
func (in *CephDeploymentCustomIngress) DeepCopy() *CephDeploymentCustomIngress {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentCustomIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentExtraOpts) DeepCopyInto(out *CephDeploymentExtraOpts) {
	*out = *in
	if in.CustomDeviceClasses != nil {
		in, out := &in.CustomDeviceClasses, &out.CustomDeviceClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeviceLabels != nil {
		in, out := &in.DeviceLabels, &out.DeviceLabels
		*out = make(map[string]LabeledDevices, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(LabeledDevices, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentExtraOpts.
func (in *CephDeploymentExtraOpts) DeepCopy() *CephDeploymentExtraOpts {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentExtraOpts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentHealth) DeepCopyInto(out *CephDeploymentHealth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentHealth.
func (in *CephDeploymentHealth) DeepCopy() *CephDeploymentHealth {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephDeploymentHealth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentHealthList) DeepCopyInto(out *CephDeploymentHealthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CephDeploymentHealth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentHealthList.
func (in *CephDeploymentHealthList) DeepCopy() *CephDeploymentHealthList {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentHealthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephDeploymentHealthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentHealthReport) DeepCopyInto(out *CephDeploymentHealthReport) {
	*out = *in
	in.RookOperator.DeepCopyInto(&out.RookOperator)
	if in.CephDaemons != nil {
		in, out := &in.CephDaemons, &out.CephDaemons
		*out = new(CephDaemonsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RookCephObjects != nil {
		in, out := &in.RookCephObjects, &out.RookCephObjects
		*out = new(RookCephObjectsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterDetails != nil {
		in, out := &in.ClusterDetails, &out.ClusterDetails
		*out = new(ClusterDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.OsdAnalysis != nil {
		in, out := &in.OsdAnalysis, &out.OsdAnalysis
		*out = new(OsdSpecAnalysisState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentHealthReport.
func (in *CephDeploymentHealthReport) DeepCopy() *CephDeploymentHealthReport {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentHealthReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentHealthStatus) DeepCopyInto(out *CephDeploymentHealthStatus) {
	*out = *in
	if in.HealthReport != nil {
		in, out := &in.HealthReport, &out.HealthReport
		*out = new(CephDeploymentHealthReport)
		(*in).DeepCopyInto(*out)
	}
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentHealthStatus.
func (in *CephDeploymentHealthStatus) DeepCopy() *CephDeploymentHealthStatus {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentHyperConverge) DeepCopyInto(out *CephDeploymentHyperConverge) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(v1.ResourceSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make(map[string]CephDeploymentToleration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentHyperConverge.
func (in *CephDeploymentHyperConverge) DeepCopy() *CephDeploymentHyperConverge {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentHyperConverge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentIngressConfig) DeepCopyInto(out *CephDeploymentIngressConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(CephDeploymentIngressTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentIngressConfig.
func (in *CephDeploymentIngressConfig) DeepCopy() *CephDeploymentIngressConfig {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentIngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentIngressTLSConfig) DeepCopyInto(out *CephDeploymentIngressTLSConfig) {
	*out = *in
	if in.TLSCerts != nil {
		in, out := &in.TLSCerts, &out.TLSCerts
		*out = new(CephDeploymentCert)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentIngressTLSConfig.
func (in *CephDeploymentIngressTLSConfig) DeepCopy() *CephDeploymentIngressTLSConfig {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentIngressTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentList) DeepCopyInto(out *CephDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CephDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentList.
func (in *CephDeploymentList) DeepCopy() *CephDeploymentList {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentMaintenance) DeepCopyInto(out *CephDeploymentMaintenance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(CephDeploymentMaintenanceStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentMaintenance.
func (in *CephDeploymentMaintenance) DeepCopy() *CephDeploymentMaintenance {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentMaintenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephDeploymentMaintenance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentMaintenanceList) DeepCopyInto(out *CephDeploymentMaintenanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CephDeploymentMaintenance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentMaintenanceList.
func (in *CephDeploymentMaintenanceList) DeepCopy() *CephDeploymentMaintenanceList {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentMaintenanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephDeploymentMaintenanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentMaintenanceStatus) DeepCopyInto(out *CephDeploymentMaintenanceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentMaintenanceStatus.
func (in *CephDeploymentMaintenanceStatus) DeepCopy() *CephDeploymentMaintenanceStatus {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentMaintenanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentNode) DeepCopyInto(out *CephDeploymentNode) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Crush != nil {
		in, out := &in.Crush, &out.Crush
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeGroup != nil {
		in, out := &in.NodeGroup, &out.NodeGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentNode.
func (in *CephDeploymentNode) DeepCopy() *CephDeploymentNode {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentSecret) DeepCopyInto(out *CephDeploymentSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(CephDeploymentSecretStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentSecret.
func (in *CephDeploymentSecret) DeepCopy() *CephDeploymentSecret {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephDeploymentSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentSecretInfo) DeepCopyInto(out *CephDeploymentSecretInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentSecretInfo.
func (in *CephDeploymentSecretInfo) DeepCopy() *CephDeploymentSecretInfo {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentSecretInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentSecretList) DeepCopyInto(out *CephDeploymentSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CephDeploymentSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentSecretList.
func (in *CephDeploymentSecretList) DeepCopy() *CephDeploymentSecretList {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephDeploymentSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentSecretStatus) DeepCopyInto(out *CephDeploymentSecretStatus) {
	*out = *in
	if in.SecretsInfo != nil {
		in, out := &in.SecretsInfo, &out.SecretsInfo
		*out = new(CephDeploymentSecretsInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentSecretStatus.
func (in *CephDeploymentSecretStatus) DeepCopy() *CephDeploymentSecretStatus {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentSecretsInfo) DeepCopyInto(out *CephDeploymentSecretsInfo) {
	*out = *in
	if in.ClientSecrets != nil {
		in, out := &in.ClientSecrets, &out.ClientSecrets
		*out = make([]CephDeploymentSecretInfo, len(*in))
		copy(*out, *in)
	}
	if in.RgwUserSecrets != nil {
		in, out := &in.RgwUserSecrets, &out.RgwUserSecrets
		*out = make([]CephDeploymentSecretInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentSecretsInfo.
func (in *CephDeploymentSecretsInfo) DeepCopy() *CephDeploymentSecretsInfo {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentSecretsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentSpec) DeepCopyInto(out *CephDeploymentSpec) {
	*out = *in
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]CephClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraOpts != nil {
		in, out := &in.ExtraOpts, &out.ExtraOpts
		*out = new(CephDeploymentExtraOpts)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(CephClusterHealthCheckSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HyperConverge != nil {
		in, out := &in.HyperConverge, &out.HyperConverge
		*out = new(CephDeploymentHyperConverge)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressConfig != nil {
		in, out := &in.IngressConfig, &out.IngressConfig
		*out = new(CephDeploymentIngressConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Mgr != nil {
		in, out := &in.Mgr, &out.Mgr
		*out = new(Mgr)
		(*in).DeepCopyInto(*out)
	}
	in.Network.DeepCopyInto(&out.Network)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]CephDeploymentNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(CephObjectStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]CephPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RBDMirror != nil {
		in, out := &in.RBDMirror, &out.RBDMirror
		*out = new(CephRBDMirrorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RookConfig != nil {
		in, out := &in.RookConfig, &out.RookConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SharedFilesystem != nil {
		in, out := &in.SharedFilesystem, &out.SharedFilesystem
		*out = new(CephSharedFilesystem)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentSpec.
func (in *CephDeploymentSpec) DeepCopy() *CephDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentStatus) DeepCopyInto(out *CephDeploymentStatus) {
	*out = *in
	in.Validation.DeepCopyInto(&out.Validation)
	if in.ObjectsRefs != nil {
		in, out := &in.ObjectsRefs, &out.ObjectsRefs
		*out = make([]corev1.ObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentStatus.
func (in *CephDeploymentStatus) DeepCopy() *CephDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentToleration) DeepCopyInto(out *CephDeploymentToleration) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentToleration.
func (in *CephDeploymentToleration) DeepCopy() *CephDeploymentToleration {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentToleration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDeploymentValidation) DeepCopyInto(out *CephDeploymentValidation) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDeploymentValidation.
func (in *CephDeploymentValidation) DeepCopy() *CephDeploymentValidation {
	if in == nil {
		return nil
	}
	out := new(CephDeploymentValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephEventDetails) DeepCopyInto(out *CephEventDetails) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]CephEventMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephEventDetails.
func (in *CephEventDetails) DeepCopy() *CephEventDetails {
	if in == nil {
		return nil
	}
	out := new(CephEventDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephEventMessage) DeepCopyInto(out *CephEventMessage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephEventMessage.
func (in *CephEventMessage) DeepCopy() *CephEventMessage {
	if in == nil {
		return nil
	}
	out := new(CephEventMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephEvents) DeepCopyInto(out *CephEvents) {
	*out = *in
	in.RebalanceDetails.DeepCopyInto(&out.RebalanceDetails)
	in.PgAutoscalerDetails.DeepCopyInto(&out.PgAutoscalerDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephEvents.
func (in *CephEvents) DeepCopy() *CephEvents {
	if in == nil {
		return nil
	}
	out := new(CephEvents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephFS) DeepCopyInto(out *CephFS) {
	*out = *in
	in.MetadataPool.DeepCopyInto(&out.MetadataPool)
	if in.DataPools != nil {
		in, out := &in.DataPools, &out.DataPools
		*out = make([]CephFSPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.MetadataServer.DeepCopyInto(&out.MetadataServer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephFS.
func (in *CephFS) DeepCopy() *CephFS {
	if in == nil {
		return nil
	}
	out := new(CephFS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephFSPool) DeepCopyInto(out *CephFSPool) {
	*out = *in
	in.CephPoolSpec.DeepCopyInto(&out.CephPoolSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephFSPool.
func (in *CephFSPool) DeepCopy() *CephFSPool {
	if in == nil {
		return nil
	}
	out := new(CephFSPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephMdsHealthCheck) DeepCopyInto(out *CephMdsHealthCheck) {
	*out = *in
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(v1.ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephMdsHealthCheck.
func (in *CephMdsHealthCheck) DeepCopy() *CephMdsHealthCheck {
	if in == nil {
		return nil
	}
	out := new(CephMdsHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephMetadataServer) DeepCopyInto(out *CephMetadataServer) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(CephMdsHealthCheck)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephMetadataServer.
func (in *CephMetadataServer) DeepCopy() *CephMetadataServer {
	if in == nil {
		return nil
	}
	out := new(CephMetadataServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephMgrModule) DeepCopyInto(out *CephMgrModule) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(CephMgrModuleSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephMgrModule.
func (in *CephMgrModule) DeepCopy() *CephMgrModule {
	if in == nil {
		return nil
	}
	out := new(CephMgrModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephMgrModuleSettings) DeepCopyInto(out *CephMgrModuleSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephMgrModuleSettings.
func (in *CephMgrModuleSettings) DeepCopy() *CephMgrModuleSettings {
	if in == nil {
		return nil
	}
	out := new(CephMgrModuleSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephMultiSite) DeepCopyInto(out *CephMultiSite) {
	*out = *in
	if in.Realms != nil {
		in, out := &in.Realms, &out.Realms
		*out = make([]CephRGWRealm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneGroups != nil {
		in, out := &in.ZoneGroups, &out.ZoneGroups
		*out = make([]CephRGWZoneGroup, len(*in))
		copy(*out, *in)
	}
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]CephRGWZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephMultiSite.
func (in *CephMultiSite) DeepCopy() *CephMultiSite {
	if in == nil {
		return nil
	}
	out := new(CephMultiSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephNetworkSpec) DeepCopyInto(out *CephNetworkSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[v1.CephNetworkType]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephNetworkSpec.
func (in *CephNetworkSpec) DeepCopy() *CephNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(CephNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephObjectStorage) DeepCopyInto(out *CephObjectStorage) {
	*out = *in
	in.Rgw.DeepCopyInto(&out.Rgw)
	if in.MultiSite != nil {
		in, out := &in.MultiSite, &out.MultiSite
		*out = new(CephMultiSite)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephObjectStorage.
func (in *CephObjectStorage) DeepCopy() *CephObjectStorage {
	if in == nil {
		return nil
	}
	out := new(CephObjectStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveTask) DeepCopyInto(out *CephOsdRemoveTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CephOsdRemoveTaskSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(CephOsdRemoveTaskStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveTask.
func (in *CephOsdRemoveTask) DeepCopy() *CephOsdRemoveTask {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephOsdRemoveTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveTaskCondition) DeepCopyInto(out *CephOsdRemoveTaskCondition) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]NodeCleanUpSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.CephClusterSpecVersion != nil {
		in, out := &in.CephClusterSpecVersion, &out.CephClusterSpecVersion
		*out = new(CephClusterSpecVersion)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveTaskCondition.
func (in *CephOsdRemoveTaskCondition) DeepCopy() *CephOsdRemoveTaskCondition {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveTaskCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveTaskList) DeepCopyInto(out *CephOsdRemoveTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CephOsdRemoveTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveTaskList.
func (in *CephOsdRemoveTaskList) DeepCopy() *CephOsdRemoveTaskList {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephOsdRemoveTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveTaskSpec) DeepCopyInto(out *CephOsdRemoveTaskSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]NodeCleanUpSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveTaskSpec.
func (in *CephOsdRemoveTaskSpec) DeepCopy() *CephOsdRemoveTaskSpec {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveTaskStatus) DeepCopyInto(out *CephOsdRemoveTaskStatus) {
	*out = *in
	if in.RemoveInfo != nil {
		in, out := &in.RemoveInfo, &out.RemoveInfo
		*out = new(TaskRemoveInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CephOsdRemoveTaskCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveTaskStatus.
func (in *CephOsdRemoveTaskStatus) DeepCopy() *CephOsdRemoveTaskStatus {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPool) DeepCopyInto(out *CephPool) {
	*out = *in
	out.StorageClassOpts = in.StorageClassOpts
	in.CephPoolSpec.DeepCopyInto(&out.CephPoolSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPool.
func (in *CephPool) DeepCopy() *CephPool {
	if in == nil {
		return nil
	}
	out := new(CephPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPoolErasureCodedSpec) DeepCopyInto(out *CephPoolErasureCodedSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPoolErasureCodedSpec.
func (in *CephPoolErasureCodedSpec) DeepCopy() *CephPoolErasureCodedSpec {
	if in == nil {
		return nil
	}
	out := new(CephPoolErasureCodedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPoolMirrorSpec) DeepCopyInto(out *CephPoolMirrorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPoolMirrorSpec.
func (in *CephPoolMirrorSpec) DeepCopy() *CephPoolMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(CephPoolMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPoolReplicatedSpec) DeepCopyInto(out *CephPoolReplicatedSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPoolReplicatedSpec.
func (in *CephPoolReplicatedSpec) DeepCopy() *CephPoolReplicatedSpec {
	if in == nil {
		return nil
	}
	out := new(CephPoolReplicatedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPoolSpec) DeepCopyInto(out *CephPoolSpec) {
	*out = *in
	if in.Replicated != nil {
		in, out := &in.Replicated, &out.Replicated
		*out = new(CephPoolReplicatedSpec)
		**out = **in
	}
	if in.ErasureCoded != nil {
		in, out := &in.ErasureCoded, &out.ErasureCoded
		*out = new(CephPoolErasureCodedSpec)
		**out = **in
	}
	if in.Mirroring != nil {
		in, out := &in.Mirroring, &out.Mirroring
		*out = new(CephPoolMirrorSpec)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnableCrushUpdates != nil {
		in, out := &in.EnableCrushUpdates, &out.EnableCrushUpdates
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPoolSpec.
func (in *CephPoolSpec) DeepCopy() *CephPoolSpec {
	if in == nil {
		return nil
	}
	out := new(CephPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRBDMirrorSecret) DeepCopyInto(out *CephRBDMirrorSecret) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRBDMirrorSecret.
func (in *CephRBDMirrorSecret) DeepCopy() *CephRBDMirrorSecret {
	if in == nil {
		return nil
	}
	out := new(CephRBDMirrorSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRBDMirrorSpec) DeepCopyInto(out *CephRBDMirrorSpec) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]CephRBDMirrorSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRBDMirrorSpec.
func (in *CephRBDMirrorSpec) DeepCopy() *CephRBDMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(CephRBDMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRGW) DeepCopyInto(out *CephRGW) {
	*out = *in
	if in.ObjectUsers != nil {
		in, out := &in.ObjectUsers, &out.ObjectUsers
		*out = make([]CephRGWUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Buckets != nil {
		in, out := &in.Buckets, &out.Buckets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int)
		**out = **in
	}
	if in.RgwUseHostNetwork != nil {
		in, out := &in.RgwUseHostNetwork, &out.RgwUseHostNetwork
		*out = new(bool)
		**out = **in
	}
	if in.MetadataPool != nil {
		in, out := &in.MetadataPool, &out.MetadataPool
		*out = new(CephPoolSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DataPool != nil {
		in, out := &in.DataPool, &out.DataPool
		*out = new(CephPoolSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Gateway.DeepCopyInto(&out.Gateway)
	if in.SSLCert != nil {
		in, out := &in.SSLCert, &out.SSLCert
		*out = new(CephDeploymentCert)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(v1.ZoneSpec)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(v1.ObjectHealthCheckSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRGW.
func (in *CephRGW) DeepCopy() *CephRGW {
	if in == nil {
		return nil
	}
	out := new(CephRGW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRGWGateway) DeepCopyInto(out *CephRGWGateway) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalRgwEndpoint != nil {
		in, out := &in.ExternalRgwEndpoint, &out.ExternalRgwEndpoint
		*out = new(v1.EndpointAddress)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRGWGateway.
func (in *CephRGWGateway) DeepCopy() *CephRGWGateway {
	if in == nil {
		return nil
	}
	out := new(CephRGWGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRGWRealm) DeepCopyInto(out *CephRGWRealm) {
	*out = *in
	if in.Pull != nil {
		in, out := &in.Pull, &out.Pull
		*out = new(CephRGWRealmPull)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRGWRealm.
func (in *CephRGWRealm) DeepCopy() *CephRGWRealm {
	if in == nil {
		return nil
	}
	out := new(CephRGWRealm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRGWRealmPull) DeepCopyInto(out *CephRGWRealmPull) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRGWRealmPull.
func (in *CephRGWRealmPull) DeepCopy() *CephRGWRealmPull {
	if in == nil {
		return nil
	}
	out := new(CephRGWRealmPull)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRGWUser) DeepCopyInto(out *CephRGWUser) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(v1.ObjectUserCapSpec)
		**out = **in
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(v1.ObjectUserQuotaSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRGWUser.
func (in *CephRGWUser) DeepCopy() *CephRGWUser {
	if in == nil {
		return nil
	}
	out := new(CephRGWUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRGWZone) DeepCopyInto(out *CephRGWZone) {
	*out = *in
	in.MetadataPool.DeepCopyInto(&out.MetadataPool)
	in.DataPool.DeepCopyInto(&out.DataPool)
	if in.EndpointsForZone != nil {
		in, out := &in.EndpointsForZone, &out.EndpointsForZone
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRGWZone.
func (in *CephRGWZone) DeepCopy() *CephRGWZone {
	if in == nil {
		return nil
	}
	out := new(CephRGWZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRGWZoneGroup) DeepCopyInto(out *CephRGWZoneGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRGWZoneGroup.
func (in *CephRGWZoneGroup) DeepCopy() *CephRGWZoneGroup {
	if in == nil {
		return nil
	}
	out := new(CephRGWZoneGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephSharedFilesystem) DeepCopyInto(out *CephSharedFilesystem) {
	*out = *in
	if in.CephFS != nil {
		in, out := &in.CephFS, &out.CephFS
		*out = make([]CephFS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephSharedFilesystem.
func (in *CephSharedFilesystem) DeepCopy() *CephSharedFilesystem {
	if in == nil {
		return nil
	}
	out := new(CephSharedFilesystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephStorageClassSpec) DeepCopyInto(out *CephStorageClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephStorageClassSpec.
func (in *CephStorageClassSpec) DeepCopy() *CephStorageClassSpec {
	if in == nil {
		return nil
	}
	out := new(CephStorageClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassUsageStats) DeepCopyInto(out *ClassUsageStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassUsageStats.
func (in *ClassUsageStats) DeepCopy() *ClassUsageStats {
	if in == nil {
		return nil
	}
	out := new(ClassUsageStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec) DeepCopyInto(out *ClientSpec) {
	*out = *in
	if in.Caps != nil {
		in, out := &in.Caps, &out.Caps
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec.
func (in *ClientSpec) DeepCopy() *ClientSpec {
	if in == nil {
		return nil
	}
	out := new(ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDetails) DeepCopyInto(out *ClusterDetails) {
	*out = *in
	if in.UsageDetails != nil {
		in, out := &in.UsageDetails, &out.UsageDetails
		*out = new(UsageDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.CephEvents != nil {
		in, out := &in.CephEvents, &out.CephEvents
		*out = new(CephEvents)
		(*in).DeepCopyInto(*out)
	}
	if in.RgwInfo != nil {
		in, out := &in.RgwInfo, &out.RgwInfo
		*out = new(RgwInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDetails.
func (in *ClusterDetails) DeepCopy() *ClusterDetails {
	if in == nil {
		return nil
	}
	out := new(ClusterDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonStatus) DeepCopyInto(out *DaemonStatus) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonStatus.
func (in *DaemonStatus) DeepCopy() *DaemonStatus {
	if in == nil {
		return nil
	}
	out := new(DaemonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceCleanupSpec) DeepCopyInto(out *DeviceCleanupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceCleanupSpec.
func (in *DeviceCleanupSpec) DeepCopy() *DeviceCleanupSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceCleanupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceInfo) DeepCopyInto(out *DeviceInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceInfo.
func (in *DeviceInfo) DeepCopy() *DeviceInfo {
	if in == nil {
		return nil
	}
	out := new(DeviceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DeviceMapping) DeepCopyInto(out *DeviceMapping) {
	{
		in := &in
		*out = make(DeviceMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceMapping.
func (in DeviceMapping) DeepCopy() DeviceMapping {
	if in == nil {
		return nil
	}
	out := new(DeviceMapping)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostMapping) DeepCopyInto(out *HostMapping) {
	*out = *in
	if in.OsdMapping != nil {
		in, out := &in.OsdMapping, &out.OsdMapping
		*out = make(map[string]OsdMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.HostRemoveStatus != nil {
		in, out := &in.HostRemoveStatus, &out.HostRemoveStatus
		*out = new(RemoveStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostMapping.
func (in *HostMapping) DeepCopy() *HostMapping {
	if in == nil {
		return nil
	}
	out := new(HostMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in LabeledDevices) DeepCopyInto(out *LabeledDevices) {
	{
		in := &in
		*out = make(LabeledDevices, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabeledDevices.
func (in LabeledDevices) DeepCopy() LabeledDevices {
	if in == nil {
		return nil
	}
	out := new(LabeledDevices)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mgr) DeepCopyInto(out *Mgr) {
	*out = *in
	if in.MgrModules != nil {
		in, out := &in.MgrModules, &out.MgrModules
		*out = make([]CephMgrModule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mgr.
func (in *Mgr) DeepCopy() *Mgr {
	if in == nil {
		return nil
	}
	out := new(Mgr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraIngress) DeepCopyInto(out *MiraIngress) {
	*out = *in
	out.CephDeploymentCert = in.CephDeploymentCert
	if in.CustomIngress != nil {
		in, out := &in.CustomIngress, &out.CustomIngress
		*out = new(CephDeploymentCustomIngress)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraIngress.
func (in *MiraIngress) DeepCopy() *MiraIngress {
	if in == nil {
		return nil
	}
	out := new(MiraIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultisiteState) DeepCopyInto(out *MultisiteState) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultisiteState.
func (in *MultisiteState) DeepCopy() *MultisiteState {
	if in == nil {
		return nil
	}
	out := new(MultisiteState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCleanUpSpec) DeepCopyInto(out *NodeCleanUpSpec) {
	*out = *in
	if in.CleanupByDevice != nil {
		in, out := &in.CleanupByDevice, &out.CleanupByDevice
		*out = make([]DeviceCleanupSpec, len(*in))
		copy(*out, *in)
	}
	if in.CleanupByOsd != nil {
		in, out := &in.CleanupByOsd, &out.CleanupByOsd
		*out = make([]OsdCleanupSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCleanUpSpec.
func (in *NodeCleanUpSpec) DeepCopy() *NodeCleanUpSpec {
	if in == nil {
		return nil
	}
	out := new(NodeCleanUpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageStatus) DeepCopyInto(out *ObjectStorageStatus) {
	*out = *in
	if in.CephObjectStores != nil {
		in, out := &in.CephObjectStores, &out.CephObjectStores
		*out = make(map[string]*v1.ObjectStoreStatus, len(*in))
		for key, val := range *in {
			var outVal *v1.ObjectStoreStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.ObjectStoreStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.CephObjectStoreUsers != nil {
		in, out := &in.CephObjectStoreUsers, &out.CephObjectStoreUsers
		*out = make(map[string]*v1.ObjectStoreUserStatus, len(*in))
		for key, val := range *in {
			var outVal *v1.ObjectStoreUserStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.ObjectStoreUserStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.ObjectBucketClaims != nil {
		in, out := &in.ObjectBucketClaims, &out.ObjectBucketClaims
		*out = make(map[string]objectbucket_iov1alpha1.ObjectBucketClaimStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CephObjectRealms != nil {
		in, out := &in.CephObjectRealms, &out.CephObjectRealms
		*out = make(map[string]*v1.Status, len(*in))
		for key, val := range *in {
			var outVal *v1.Status
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.Status)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.CephObjectZoneGroups != nil {
		in, out := &in.CephObjectZoneGroups, &out.CephObjectZoneGroups
		*out = make(map[string]*v1.Status, len(*in))
		for key, val := range *in {
			var outVal *v1.Status
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.Status)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.CephObjectZones != nil {
		in, out := &in.CephObjectZones, &out.CephObjectZones
		*out = make(map[string]*v1.Status, len(*in))
		for key, val := range *in {
			var outVal *v1.Status
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.Status)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageStatus.
func (in *ObjectStorageStatus) DeepCopy() *ObjectStorageStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsdCleanupSpec) DeepCopyInto(out *OsdCleanupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsdCleanupSpec.
func (in *OsdCleanupSpec) DeepCopy() *OsdCleanupSpec {
	if in == nil {
		return nil
	}
	out := new(OsdCleanupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsdDetails) DeepCopyInto(out *OsdDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsdDetails.
func (in *OsdDetails) DeepCopy() *OsdDetails {
	if in == nil {
		return nil
	}
	out := new(OsdDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsdMapping) DeepCopyInto(out *OsdMapping) {
	*out = *in
	if in.DeviceMapping != nil {
		in, out := &in.DeviceMapping, &out.DeviceMapping
		*out = make(map[string]DeviceInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RemoveStatus != nil {
		in, out := &in.RemoveStatus, &out.RemoveStatus
		*out = new(RemoveResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsdMapping.
func (in *OsdMapping) DeepCopy() *OsdMapping {
	if in == nil {
		return nil
	}
	out := new(OsdMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsdSpecAnalysisState) DeepCopyInto(out *OsdSpecAnalysisState) {
	*out = *in
	in.DiskDaemon.DeepCopyInto(&out.DiskDaemon)
	if in.CephClusterSpecGeneration != nil {
		in, out := &in.CephClusterSpecGeneration, &out.CephClusterSpecGeneration
		*out = new(int64)
		**out = **in
	}
	if in.SpecAnalysis != nil {
		in, out := &in.SpecAnalysis, &out.SpecAnalysis
		*out = make(map[string]DaemonStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsdSpecAnalysisState.
func (in *OsdSpecAnalysisState) DeepCopy() *OsdSpecAnalysisState {
	if in == nil {
		return nil
	}
	out := new(OsdSpecAnalysisState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolUsageStats) DeepCopyInto(out *PoolUsageStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolUsageStats.
func (in *PoolUsageStats) DeepCopy() *PoolUsageStats {
	if in == nil {
		return nil
	}
	out := new(PoolUsageStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveResult) DeepCopyInto(out *RemoveResult) {
	*out = *in
	if in.OsdRemoveStatus != nil {
		in, out := &in.OsdRemoveStatus, &out.OsdRemoveStatus
		*out = new(RemoveStatus)
		**out = **in
	}
	if in.DeployRemoveStatus != nil {
		in, out := &in.DeployRemoveStatus, &out.DeployRemoveStatus
		*out = new(RemoveStatus)
		**out = **in
	}
	if in.DeviceCleanUpJob != nil {
		in, out := &in.DeviceCleanUpJob, &out.DeviceCleanUpJob
		*out = new(RemoveStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveResult.
func (in *RemoveResult) DeepCopy() *RemoveResult {
	if in == nil {
		return nil
	}
	out := new(RemoveResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveStatus) DeepCopyInto(out *RemoveStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveStatus.
func (in *RemoveStatus) DeepCopy() *RemoveStatus {
	if in == nil {
		return nil
	}
	out := new(RemoveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RgwInfo) DeepCopyInto(out *RgwInfo) {
	*out = *in
	if in.MultisiteDetails != nil {
		in, out := &in.MultisiteDetails, &out.MultisiteDetails
		*out = new(MultisiteState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RgwInfo.
func (in *RgwInfo) DeepCopy() *RgwInfo {
	if in == nil {
		return nil
	}
	out := new(RgwInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RookCephObjectsStatus) DeepCopyInto(out *RookCephObjectsStatus) {
	*out = *in
	if in.CephCluster != nil {
		in, out := &in.CephCluster, &out.CephCluster
		*out = new(v1.ClusterStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockStorage != nil {
		in, out := &in.BlockStorage, &out.BlockStorage
		*out = new(BlockStorageStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CephClients != nil {
		in, out := &in.CephClients, &out.CephClients
		*out = make(map[string]*v1.CephClientStatus, len(*in))
		for key, val := range *in {
			var outVal *v1.CephClientStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.CephClientStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(ObjectStorageStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SharedFilesystem != nil {
		in, out := &in.SharedFilesystem, &out.SharedFilesystem
		*out = new(SharedFilesystemStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RookCephObjectsStatus.
func (in *RookCephObjectsStatus) DeepCopy() *RookCephObjectsStatus {
	if in == nil {
		return nil
	}
	out := new(RookCephObjectsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedFilesystemStatus) DeepCopyInto(out *SharedFilesystemStatus) {
	*out = *in
	if in.CephFilesystems != nil {
		in, out := &in.CephFilesystems, &out.CephFilesystems
		*out = make(map[string]*v1.CephFilesystemStatus, len(*in))
		for key, val := range *in {
			var outVal *v1.CephFilesystemStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(v1.CephFilesystemStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedFilesystemStatus.
func (in *SharedFilesystemStatus) DeepCopy() *SharedFilesystemStatus {
	if in == nil {
		return nil
	}
	out := new(SharedFilesystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRemoveInfo) DeepCopyInto(out *TaskRemoveInfo) {
	*out = *in
	if in.CleanupMap != nil {
		in, out := &in.CleanupMap, &out.CleanupMap
		*out = make(map[string]HostMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRemoveInfo.
func (in *TaskRemoveInfo) DeepCopy() *TaskRemoveInfo {
	if in == nil {
		return nil
	}
	out := new(TaskRemoveInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageDetails) DeepCopyInto(out *UsageDetails) {
	*out = *in
	if in.ClassesDetail != nil {
		in, out := &in.ClassesDetail, &out.ClassesDetail
		*out = make(map[string]ClassUsageStats, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PoolsDetail != nil {
		in, out := &in.PoolsDetail, &out.PoolsDetail
		*out = make(map[string]PoolUsageStats, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageDetails.
func (in *UsageDetails) DeepCopy() *UsageDetails {
	if in == nil {
		return nil
	}
	out := new(UsageDetails)
	in.DeepCopyInto(out)
	return out
}
